#!/usr/bin/env node

function printUsage() {
  console.log('Usage: node skills/hello/hello.js [name]');
  console.log('Outputs a friendly greeting sourced from the CrewX hello skill.');
}

const args = process.argv.slice(2);

if (args.includes('--help') || args.includes('-h')) {
  printUsage();
  process.exit(0);
}

const name = args[0] ?? 'CrewX user';
const message = `Hello, ${name}! This message is generated by the CrewX hello skill script.`;

console.log(message);
