name: Bug Report
description: Report a reproducible problem in the CrewX monorepo
title: "[Bug]: "
labels: ["type:bug", "status:triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include screenshots or console output if relevant)
      placeholder: Describe what happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of CrewX is affected?
      multiple: true
      options:
        - CLI (packages/cli)
        - SDK (packages/sdk)
        - Slack Bot
        - MCP Server
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, cosmetic)
    validations:
      required: true

  - type: input
    id: crewx-version
    attributes:
      label: CrewX Version
      description: Run `crewx --version` to get this
      placeholder: "e.g., 0.7.7"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version` to get this
      placeholder: "e.g., v20.19.2"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Traces
      description: Paste any relevant logs (will be automatically formatted as code)
      render: shell
      placeholder: |
        Paste error messages or logs here...

  - type: textarea
    id: workaround
    attributes:
      label: Temporary Workarounds
      description: Have you found a workaround?
      placeholder: Describe any workarounds you've found...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (linked issues, PRs, configs, etc.)
      placeholder: Add any other context...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have run `npm run build` to ensure the latest code is compiled
          required: false
        - label: I can reproduce this bug consistently
          required: false
