/**
 * crewx init handler.
 * Initializes a CrewX project by creating crewx.yaml and supporting dirs.
 *
 * Usage:
 *   crewx init                     Create crewx.yaml in current directory
 *   crewx init --force             Overwrite existing configuration
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { handleHookInstall } from './hook/install';
import { findProjectRoot } from './hook/paths';

const DEFAULT_AGENTS = [
  {
    id: 'planner',
    name: 'Planner',
    role: 'Product/Architecture Planner',
    team: 'core',
    provider: 'cli/claude',
    default_model: 'claude-opus-4-7',
    working_directory: './',
    description: '요구 분석·설계·작업 분해를 담당',
    system_prompt: `You are a planner. Break down user goals into concrete,\ntestable steps. Challenge assumptions. Never write code directly.`,
  },
  {
    id: 'developer',
    name: 'Developer',
    role: 'Implementation Engineer',
    team: 'core',
    provider: 'cli/claude',
    default_model: 'claude-opus-4-7',
    working_directory: './',
    description: '실제 코드 작성과 테스트',
    system_prompt: `Implement what the planner specifies. Prefer editing\nexisting files. Run tests before reporting done.`,
  },
  {
    id: 'reviewer',
    name: 'Reviewer',
    role: 'Code Reviewer',
    team: 'core',
    provider: 'cli/claude',
    default_model: 'claude-opus-4-7',
    working_directory: './',
    description: '코드 품질·보안·가독성 리뷰',
    system_prompt: `Review diffs for correctness, security, readability.\nCite file:line. Be blunt, not polite.`,
  },
];

function escapeYamlBlock(text: string): string {
  return text
    .split('\n')
    .map((line) => `      ${line}`)
    .join('\n');
}

function generateDefaultYaml(agents: typeof DEFAULT_AGENTS): string {
  const agentBlocks = agents
    .map(
      (a) =>
        `  - id: "${a.id}"
    name: "${a.name}"
    role: "${a.role}"
    team: "${a.team}"
    provider: "${a.provider}"
    default_model: "${a.default_model}"
    working_directory: "${a.working_directory}"
    description: "${a.description}"
    system_prompt: |
${escapeYamlBlock(a.system_prompt)}`,
    )
    .join('\n\n');

  return `# CrewX Agents Configuration
# Generated by 'crewx init'

agents:
${agentBlocks}

# Usage examples:
#   crewx query "@planner analyze this codebase"
#   crewx execute "@developer implement the feature described above"
#   crewx agent ls
`;
}

export interface InitResult {
  yamlCreated: boolean;
  hookInstalled: boolean;
  errors: string[];
  skippedReason?: 'yaml-exists' | 'nested-project';
}

/**
 * Programmatic init — creates crewx.yaml, support dirs, and optionally installs hooks.
 * Throws on unrecoverable errors (PATH_NOT_FOUND, NESTED_CREWX_PROJECT, YAML_CREATE_FAILED).
 * Partial failures (hook install, mkdir) are collected in InitResult.errors without rollback.
 */
export async function handleInit(opts: {
  path: string;
  skipHook?: boolean;
  force?: boolean;
}): Promise<InitResult> {
  const { path: target, skipHook = false, force = false } = opts;
  const errors: string[] = [];
  let yamlCreated = false;
  let hookInstalled = false;

  if (!existsSync(target)) {
    throw new Error(`PATH_NOT_FOUND: ${target}`);
  }

  // Reject if a parent directory already owns a crewx project
  const parentRoot = findProjectRoot(dirname(target));
  if (parentRoot && parentRoot !== target) {
    throw new Error(`NESTED_CREWX_PROJECT: parent root at ${parentRoot}`);
  }

  const yamlPath = join(target, 'crewx.yaml');
  const ymlPath = join(target, 'crewx.yml');
  if (existsSync(yamlPath) || existsSync(ymlPath)) {
    if (!force) {
      return { yamlCreated: false, hookInstalled: false, errors: [], skippedReason: 'yaml-exists' };
    }
  }

  try {
    const content = generateDefaultYaml(DEFAULT_AGENTS);
    writeFileSync(yamlPath, content, 'utf-8');
    yamlCreated = true;
  } catch (e: any) {
    throw new Error(`YAML_CREATE_FAILED: ${e.message}`);
  }

  for (const dir of ['.crewx/logs', '.claude/commands']) {
    try {
      mkdirSync(join(target, dir), { recursive: true });
    } catch (e: any) {
      errors.push(`MKDIR_FAILED:${dir}:${e.message}`);
    }
  }

  if (!skipHook) {
    try {
      await handleHookInstall({ projectRoot: target, yes: true });
      hookInstalled = true;
    } catch (e: any) {
      errors.push(`HOOK_INSTALL_FAILED: ${e.message}`);
    }
  }

  return { yamlCreated, hookInstalled, errors };
}
