name: Nightly Build

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    name: Nightly Build & Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Run full test suite
        run: npm run test:ci

      - name: Smoke test SDK
        run: |
          cd packages/sdk
          node -e "const sdk = require('./dist/index.js'); console.log('SDK loaded:', !!sdk);"

      - name: Smoke test CLI
        run: |
          cd packages/cli
          node dist/main.js --version || echo "CLI version check"
          node dist/main.js --help || echo "CLI help check"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Nightly Build Failed',
              body: `Nightly build failed on ${new Date().toISOString()}\n\nWorkflow: ${context.workflow}\nRun: ${context.runNumber}`,
              labels: ['ci', 'nightly-failure']
            })
